// Static factory source for dynamic execute modules. Do not serialize bundled
// functions with Function.prototype.toString() here — production wrangler/esbuild
// can rewrite named functions to use a bundle-scoped __name helper that does not
// exist inside dynamically loaded worker modules.
export const kodyRemoteProxyFactorySource = [
	'function createKodyRemoteProxy(input) {',
	'  const entityLabel = input.entityLabel || "MCP server";',
	'  const shortEntityLabel = input.shortEntityLabel || "MCP server";',
	'  const capabilityLabel = input.capabilityLabel || "MCP tool";',
	'  const entries = new Map(',
	'    input.entries.map((entry) => [',
	'      entry.name,',
	'      {',
	'        ...entry,',
	'        capabilitiesByName: new Map(',
	'          entry.capabilities.map((capability) => [',
	'            capability.name,',
	'            capability,',
	'          ]),',
	'        ),',
	'      },',
	'    ]),',
	'  );',
	'  const formatNames = (names) =>',
	'    names.length > 0',
	'      ? names.map((name) => JSON.stringify(name)).join(", ")',
	'      : "none";',
	'  const isProxyLookupKey = (name) =>',
	'    typeof name === "symbol" || name === "then";',
	'  // Bundlers rewrite repeated kody.mcp["home"].tool() access into',
	'  // destructuring (`const { home } = kody.mcp`). Proxies that only',
	'  // implement [[Get]] make that home binding undefined. Unknown names',
	'  // must throw here too — returning undefined lets `home` bind silently',
	'  // and later fail as `Cannot read properties of undefined`.',
	'  const createReflectingProxy = (knownKeys, getValue) =>',
	'    new Proxy(',
	'      {},',
	'      {',
	'        get(_target, name) {',
	'          if (isProxyLookupKey(name)) return undefined;',
	'          return getValue(String(name));',
	'        },',
	'        has(_target, name) {',
	'          if (isProxyLookupKey(name)) return false;',
	'          return knownKeys.includes(String(name));',
	'        },',
	'        ownKeys() {',
	'          return [...knownKeys];',
	'        },',
	'        getOwnPropertyDescriptor(_target, name) {',
	'          if (isProxyLookupKey(name)) return undefined;',
	'          return {',
	'            configurable: true,',
	'            enumerable: true,',
	'            writable: true,',
	'            value: getValue(String(name)),',
	'          };',
	'        },',
	'      },',
	'    );',
	'',
	'  const createCapabilityProxy = (entry, entryName) =>',
	'    createReflectingProxy(',
	'      entry.capabilities.map((capability) => capability.name),',
	'      (capabilityName) => {',
	'        const capability = entry.capabilitiesByName.get(capabilityName);',
	'        if (!capability) {',
	'          if (!entry.status.connected || entry.status.toolCount === 0) {',
	'            throw new Error(entry.status.unavailableMessage);',
	'          }',
	'          throw new Error(',
	'            "Unknown " +',
	'              capabilityLabel +',
	'              " \\"" +',
	'              capabilityName +',
	'              "\\" for " +',
	'              shortEntityLabel +',
	'              " \\"" +',
	'              entryName +',
	'              "\\". Available capabilities: " +',
	'              formatNames(',
	'                entry.capabilities.map((capabilityEntry) => capabilityEntry.name),',
	'              ) +',
	'              ".",',
	'          );',
	'        }',
	'        return async (args) => {',
	'          if (!entry.status.connected || entry.status.toolCount === 0) {',
	'            throw new Error(entry.status.unavailableMessage);',
	'          }',
	'          return await input.callTool(capability.dispatchName, args);',
	'        };',
	'      },',
	'    );',
	'',
	'  return createReflectingProxy([...entries.keys()], (entryName) => {',
	'    const entry = entries.get(entryName);',
	'    if (!entry) {',
	'      throw new Error(',
	'        "Unknown " +',
	'          entityLabel +',
	'          " \\"" +',
	'          entryName +',
	'          "\\". Available " +',
	'          entityLabel +',
	'          "s: " +',
	'          formatNames([...entries.keys()]) +',
	'          ".",',
	'      );',
	'    }',
	'    return createCapabilityProxy(entry, entryName);',
	'  });',
	'}',
].join('\n')

export function assertGeneratedExecutorSourceIsBundleSafe(source: string) {
	if (/\b__name\b/u.test(source)) {
		throw new Error(
			'Generated executor source must not reference bundle-scoped __name helpers.',
		)
	}
}
