-- Squashed baseline schema (2026-08-04).
--
-- Generated by replaying the full ledgered migration history 0001-init.sql
-- through 0144-drop-jobs-observability-columns.sql (145 files, final
-- pre-squash main commit 63616db6) against a fresh local D1 database and
-- dumping schema plus migration-seeded platform rows (RBAC roles and
-- permissions, the system/user email graph authority markers, and the
-- d1_storage_reconcile_cursor row).
--
-- The pre-squash history remains available in Git history at tag-time; the
-- d1_migrations bookkeeping reset that pairs with this file lives in
-- tools/ci/reset-migration-bookkeeping.ts and is invoked by the preview and
-- production deploy workflows before "wrangler d1 migrations apply".
--
-- This filename is deliberately NOT 0001-init.sql: a pre-squash checkout
-- deploying against post-squash bookkeeping must fail fast on its first
-- CREATE TABLE instead of silently re-applying history.

PRAGMA defer_foreign_keys = TRUE;

CREATE TABLE password_resets (
	id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
	user_id INTEGER NOT NULL,
	token_hash TEXT NOT NULL UNIQUE,
	expires_at INTEGER NOT NULL,
	created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP),
	FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);
CREATE TABLE value_buckets (
	id TEXT PRIMARY KEY NOT NULL,
	user_id TEXT NOT NULL,
	scope TEXT NOT NULL CHECK (scope IN ('session', 'app', 'user')),
	binding_key TEXT NOT NULL,
	expires_at TEXT,
	created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP),
	updated_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP),
	UNIQUE(user_id, scope, binding_key)
);
CREATE TABLE value_entries (
	bucket_id TEXT NOT NULL,
	name TEXT NOT NULL,
	description TEXT NOT NULL DEFAULT '',
	value TEXT NOT NULL,
	created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP),
	updated_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP),
	PRIMARY KEY (bucket_id, name),
	FOREIGN KEY (bucket_id) REFERENCES value_buckets(id) ON DELETE CASCADE
);
CREATE TABLE mcp_user_server_instructions (
	user_id TEXT PRIMARY KEY NOT NULL,
	instructions TEXT NOT NULL,
	updated_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP)
);
CREATE TABLE mcp_memories (
	id TEXT PRIMARY KEY NOT NULL,
	user_id TEXT NOT NULL,
	category TEXT,
	status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'deleted', 'archived')),
	subject TEXT NOT NULL,
	summary TEXT NOT NULL,
	details TEXT NOT NULL DEFAULT '',
	tags_json TEXT NOT NULL DEFAULT '[]',
	dedupe_key TEXT,
	created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP),
	updated_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP),
	last_accessed_at TEXT,
	deleted_at TEXT
, source_uris_json TEXT NOT NULL DEFAULT '[]');
CREATE TABLE mcp_memory_conversation_suppressions (
	user_id TEXT NOT NULL,
	conversation_id TEXT NOT NULL,
	memory_id TEXT NOT NULL,
	created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP),
	last_seen_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP),
	expires_at TEXT NOT NULL,
	PRIMARY KEY (user_id, conversation_id, memory_id),
	FOREIGN KEY (memory_id) REFERENCES mcp_memories(id) ON DELETE CASCADE
);
CREATE TABLE entity_sources (
	id TEXT PRIMARY KEY,
	user_id TEXT NOT NULL,
	entity_kind TEXT NOT NULL,
	entity_id TEXT NOT NULL,
	repo_id TEXT NOT NULL,
	published_commit TEXT,
	indexed_commit TEXT,
	manifest_path TEXT NOT NULL DEFAULT 'kody.json',
	source_root TEXT NOT NULL DEFAULT '/',
	created_at TEXT NOT NULL,
	updated_at TEXT NOT NULL
, last_external_check_at TEXT, external_check_until TEXT);
CREATE TABLE IF NOT EXISTS "jobs" (
	id TEXT PRIMARY KEY NOT NULL,
	user_id TEXT NOT NULL,
	name TEXT NOT NULL,
	source_id TEXT NOT NULL,
	published_commit TEXT,
	repo_check_policy_json TEXT,
	storage_id TEXT NOT NULL,
	params_json TEXT,
	schedule_json TEXT NOT NULL,
	timezone TEXT NOT NULL,
	enabled INTEGER NOT NULL DEFAULT 1 CHECK (enabled IN (0, 1)),
	kill_switch_enabled INTEGER NOT NULL DEFAULT 0 CHECK (kill_switch_enabled IN (0, 1)),
	caller_context_json TEXT NOT NULL,
	created_at TEXT NOT NULL,
	updated_at TEXT NOT NULL,
	last_run_at TEXT,
	last_run_status TEXT,
	next_run_at TEXT NOT NULL,
	preserved INTEGER NOT NULL DEFAULT 0
	CHECK (preserved IN (0, 1)), claim_token TEXT, running_since TEXT, lease_expires_at TEXT, claimed_scheduled_for TEXT, retry_scheduled_for TEXT, retry_count INTEGER NOT NULL DEFAULT 0, last_completed_scheduled_for TEXT, expires_at TEXT);
CREATE TABLE saved_packages (
	id TEXT PRIMARY KEY NOT NULL,
	user_id TEXT NOT NULL,
	name TEXT NOT NULL,
	kody_id TEXT NOT NULL,
	description TEXT NOT NULL,
	tags_json TEXT NOT NULL DEFAULT '[]',
	search_text TEXT,
	source_id TEXT NOT NULL,
	has_app INTEGER NOT NULL DEFAULT 0 CHECK (has_app IN (0, 1)),
	created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP),
	updated_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP)
, hidden INTEGER NOT NULL DEFAULT 0 CHECK (hidden IN (0, 1)), is_private INTEGER NOT NULL DEFAULT 1 CHECK (is_private IN (0, 1)));
CREATE TABLE published_bundle_artifacts (
	id TEXT PRIMARY KEY,
	user_id TEXT NOT NULL,
	source_id TEXT NOT NULL,
	published_commit TEXT NOT NULL,
	artifact_kind TEXT NOT NULL,
	artifact_name TEXT,
	entry_point TEXT NOT NULL,
	kv_key TEXT NOT NULL,
	dependencies_json TEXT NOT NULL DEFAULT '[]',
	created_at TEXT NOT NULL,
	updated_at TEXT NOT NULL
);
CREATE TABLE archived_job_artifacts (
	id TEXT PRIMARY KEY,
	job_id TEXT NOT NULL UNIQUE,
	user_id TEXT NOT NULL,
	source_id TEXT NOT NULL,
	published_commit TEXT NOT NULL,
	storage_id TEXT NOT NULL,
	retain_until TEXT NOT NULL,
	created_at TEXT NOT NULL,
	updated_at TEXT NOT NULL
);
CREATE TABLE package_invocation_tokens (
	id TEXT PRIMARY KEY,
	user_id TEXT NOT NULL,
	name TEXT NOT NULL,
	token_hash TEXT NOT NULL UNIQUE,
	email TEXT NOT NULL,
	display_name TEXT NOT NULL,
	package_ids_json TEXT NOT NULL DEFAULT '[]',
	package_kody_ids_json TEXT NOT NULL DEFAULT '[]',
	export_names_json TEXT NOT NULL DEFAULT '[]',
	sources_json TEXT NOT NULL DEFAULT '[]',
	created_at TEXT NOT NULL,
	updated_at TEXT NOT NULL,
	last_used_at TEXT,
	revoked_at TEXT
);
CREATE TABLE IF NOT EXISTS "email_inboxes" (
	id TEXT PRIMARY KEY,
	user_id TEXT NOT NULL,
	package_id TEXT,
	name TEXT NOT NULL,
	description TEXT NOT NULL DEFAULT '',
	enabled INTEGER NOT NULL DEFAULT 1 CHECK (enabled IN (0, 1)),
	created_at TEXT NOT NULL,
	updated_at TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS "email_inbox_addresses" (
	id TEXT PRIMARY KEY,
	inbox_id TEXT NOT NULL,
	user_id TEXT NOT NULL,
	address TEXT NOT NULL,
	local_part TEXT NOT NULL,
	domain TEXT NOT NULL,
	enabled INTEGER NOT NULL DEFAULT 1 CHECK (enabled IN (0, 1)),
	created_at TEXT NOT NULL,
	updated_at TEXT NOT NULL,
	FOREIGN KEY (inbox_id) REFERENCES "email_inboxes"(id) ON DELETE CASCADE
);
CREATE TABLE repo_sessions (
	id TEXT PRIMARY KEY,
	user_id TEXT NOT NULL,
	source_id TEXT NOT NULL,
	source_repo_id TEXT NOT NULL,
	session_branch TEXT NOT NULL,
	source_branch TEXT NOT NULL,
	base_commit TEXT NOT NULL,
	source_root TEXT NOT NULL DEFAULT '/',
	conversation_id TEXT,
	status TEXT NOT NULL DEFAULT 'active',
	expires_at TEXT,
	last_checkpoint_at TEXT,
	last_checkpoint_commit TEXT,
	last_check_run_id TEXT,
	last_check_tree_hash TEXT,
	created_at TEXT NOT NULL,
	updated_at TEXT NOT NULL
);
CREATE TABLE roles (
	id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
	name TEXT NOT NULL UNIQUE,
	description TEXT NOT NULL DEFAULT '',
	created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP),
	updated_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP)
);
INSERT INTO roles VALUES(1,'user','Default role for every account','2026-08-04 20:55:22','2026-08-04 20:55:22');
INSERT INTO roles VALUES(2,'admin','Operator role','2026-08-04 20:55:22','2026-08-04 20:55:22');
CREATE TABLE permissions (
	id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
	action TEXT NOT NULL,
	entity TEXT NOT NULL,
	access TEXT NOT NULL,
	description TEXT NOT NULL DEFAULT '',
	created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP),
	updated_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP),
	UNIQUE (action, entity, access)
);
INSERT INTO permissions VALUES(1,'create','user','own','','2026-08-04 20:55:22','2026-08-04 20:55:22');
INSERT INTO permissions VALUES(2,'read','user','own','','2026-08-04 20:55:22','2026-08-04 20:55:22');
INSERT INTO permissions VALUES(3,'update','user','own','','2026-08-04 20:55:22','2026-08-04 20:55:22');
INSERT INTO permissions VALUES(4,'delete','user','own','','2026-08-04 20:55:22','2026-08-04 20:55:22');
INSERT INTO permissions VALUES(5,'create','role','own','','2026-08-04 20:55:22','2026-08-04 20:55:22');
INSERT INTO permissions VALUES(6,'read','role','own','','2026-08-04 20:55:22','2026-08-04 20:55:22');
INSERT INTO permissions VALUES(7,'update','role','own','','2026-08-04 20:55:22','2026-08-04 20:55:22');
INSERT INTO permissions VALUES(8,'delete','role','own','','2026-08-04 20:55:22','2026-08-04 20:55:22');
INSERT INTO permissions VALUES(9,'create','user','any','','2026-08-04 20:55:22','2026-08-04 20:55:22');
INSERT INTO permissions VALUES(10,'read','user','any','','2026-08-04 20:55:22','2026-08-04 20:55:22');
INSERT INTO permissions VALUES(11,'update','user','any','','2026-08-04 20:55:22','2026-08-04 20:55:22');
INSERT INTO permissions VALUES(12,'delete','user','any','','2026-08-04 20:55:22','2026-08-04 20:55:22');
INSERT INTO permissions VALUES(13,'create','role','any','','2026-08-04 20:55:22','2026-08-04 20:55:22');
INSERT INTO permissions VALUES(14,'read','role','any','','2026-08-04 20:55:22','2026-08-04 20:55:22');
INSERT INTO permissions VALUES(15,'update','role','any','','2026-08-04 20:55:22','2026-08-04 20:55:22');
INSERT INTO permissions VALUES(16,'delete','role','any','','2026-08-04 20:55:22','2026-08-04 20:55:22');
CREATE TABLE role_permissions (
	role_id INTEGER NOT NULL,
	permission_id INTEGER NOT NULL,
	PRIMARY KEY (role_id, permission_id),
	FOREIGN KEY (role_id) REFERENCES roles(id) ON DELETE CASCADE,
	FOREIGN KEY (permission_id) REFERENCES permissions(id) ON DELETE CASCADE
);
INSERT INTO role_permissions VALUES(1,5);
INSERT INTO role_permissions VALUES(1,1);
INSERT INTO role_permissions VALUES(1,8);
INSERT INTO role_permissions VALUES(1,4);
INSERT INTO role_permissions VALUES(1,6);
INSERT INTO role_permissions VALUES(1,2);
INSERT INTO role_permissions VALUES(1,7);
INSERT INTO role_permissions VALUES(1,3);
INSERT INTO role_permissions VALUES(2,13);
INSERT INTO role_permissions VALUES(2,5);
INSERT INTO role_permissions VALUES(2,9);
INSERT INTO role_permissions VALUES(2,1);
INSERT INTO role_permissions VALUES(2,16);
INSERT INTO role_permissions VALUES(2,8);
INSERT INTO role_permissions VALUES(2,12);
INSERT INTO role_permissions VALUES(2,4);
INSERT INTO role_permissions VALUES(2,14);
INSERT INTO role_permissions VALUES(2,6);
INSERT INTO role_permissions VALUES(2,10);
INSERT INTO role_permissions VALUES(2,2);
INSERT INTO role_permissions VALUES(2,15);
INSERT INTO role_permissions VALUES(2,7);
INSERT INTO role_permissions VALUES(2,11);
INSERT INTO role_permissions VALUES(2,3);
CREATE TABLE user_roles (
	user_id INTEGER NOT NULL,
	role_id INTEGER NOT NULL,
	created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP),
	PRIMARY KEY (user_id, role_id),
	FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
	FOREIGN KEY (role_id) REFERENCES roles(id) ON DELETE CASCADE
);
CREATE TABLE community_listings (
	id TEXT PRIMARY KEY NOT NULL,
	owner_user_id TEXT NOT NULL,
	package_id TEXT NOT NULL,
	source_id TEXT NOT NULL,
	kody_id TEXT NOT NULL,
	name TEXT NOT NULL,
	description TEXT NOT NULL,
	tags_json TEXT NOT NULL DEFAULT '[]',
	search_text TEXT,
	readme_content TEXT,
	license TEXT NOT NULL,
	pinned_commit TEXT NOT NULL,
	status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'delisted')),
	created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP),
	updated_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP),
	published_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP)
, trusted_commit TEXT, trusted_by_user_id TEXT, trusted_at TEXT, featured_at TEXT);
CREATE TABLE community_ratings (
	id TEXT PRIMARY KEY NOT NULL,
	listing_id TEXT NOT NULL,
	user_id TEXT NOT NULL,
	stars INTEGER NOT NULL CHECK (stars BETWEEN 1 AND 5),
	adaptation_effort INTEGER NOT NULL CHECK (adaptation_effort BETWEEN 1 AND 5),
	note TEXT,
	created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP),
	updated_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP)
);
CREATE TABLE community_reports (
	id TEXT PRIMARY KEY NOT NULL,
	listing_id TEXT NOT NULL,
	listing_name TEXT NOT NULL,
	listing_owner_user_id TEXT NOT NULL,
	reporter_user_id TEXT NOT NULL,
	reason TEXT NOT NULL,
	status TEXT NOT NULL DEFAULT 'open' CHECK (status IN ('open', 'resolved', 'dismissed')),
	resolved_by_user_id TEXT,
	resolved_at TEXT,
	resolution_note TEXT,
	created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP),
	updated_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP)
);
CREATE TABLE community_bans (
	user_id TEXT PRIMARY KEY NOT NULL,
	banned_by_user_id TEXT NOT NULL,
	reason TEXT NOT NULL,
	created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP)
);
CREATE TABLE email_verifications (
	id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
	user_id INTEGER NOT NULL,
	token_hash TEXT NOT NULL UNIQUE,
	expires_at INTEGER NOT NULL,
	created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP),
	FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);
CREATE TABLE usage_rollups (
	user_id TEXT NOT NULL,
	metric TEXT NOT NULL,
	month TEXT NOT NULL,
	event_count INTEGER NOT NULL DEFAULT 0,
	error_count INTEGER NOT NULL DEFAULT 0,
	total_duration_ms INTEGER NOT NULL DEFAULT 0,
	total_cpu_ms INTEGER NOT NULL DEFAULT 0,
	total_bytes INTEGER NOT NULL DEFAULT 0,
	updated_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP),
	PRIMARY KEY (user_id, metric, month)
);
CREATE TABLE IF NOT EXISTS "remote_connector_settings" (
	id TEXT PRIMARY KEY NOT NULL,
	user_id TEXT NOT NULL,
	instance_id TEXT NOT NULL,
	enabled INTEGER NOT NULL DEFAULT 1 CHECK (enabled IN (0, 1)),
	attached INTEGER NOT NULL DEFAULT 1 CHECK (attached IN (0, 1)),
	encrypted_shared_secret TEXT,
	created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ', 'now')),
	updated_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ', 'now')),
	UNIQUE(user_id, instance_id)
);
CREATE TABLE system_email_daily_counters (
	local_part TEXT NOT NULL,
	day TEXT NOT NULL,
	count INTEGER NOT NULL DEFAULT 0,
	updated_at TEXT NOT NULL, operation_token TEXT,
	PRIMARY KEY (local_part, day)
);
CREATE TABLE pending_email_changes (
	id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
	user_id INTEGER NOT NULL,
	new_email TEXT NOT NULL,
	token_hash TEXT NOT NULL UNIQUE,
	expires_at INTEGER NOT NULL,
	created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP),
	FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);
CREATE TABLE mcp_server_settings (
	id TEXT PRIMARY KEY NOT NULL,
	user_id TEXT NOT NULL,
	name TEXT NOT NULL,
	url TEXT NOT NULL,
	enabled INTEGER NOT NULL DEFAULT 1 CHECK (enabled IN (0, 1)),
	created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ', 'now')),
	updated_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ', 'now')),
	UNIQUE(user_id, name)
);
CREATE TABLE verifications (
	id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
	type TEXT NOT NULL,
	target TEXT NOT NULL,
	secret TEXT NOT NULL,
	algorithm TEXT NOT NULL,
	digits INTEGER NOT NULL,
	period INTEGER NOT NULL,
	char_set TEXT NOT NULL,
	expires_at INTEGER,
	created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP),
	UNIQUE (target, type)
);
CREATE TABLE passkeys (
	id TEXT PRIMARY KEY NOT NULL,
	aaguid TEXT NOT NULL,
	public_key TEXT NOT NULL,
	user_id INTEGER NOT NULL,
	webauthn_user_handle TEXT NOT NULL,
	counter INTEGER NOT NULL DEFAULT 0,
	device_type TEXT NOT NULL,
	backed_up INTEGER NOT NULL DEFAULT 0,
	transports TEXT,
	created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP),
	updated_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP), name TEXT NOT NULL DEFAULT '', last_used_at TEXT,
	FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);
CREATE TABLE oauth_connections (
	id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
	provider_name TEXT NOT NULL,
	provider_id TEXT NOT NULL,
	user_id INTEGER NOT NULL,
	provider_display_name TEXT,
	created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP),
	updated_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP),
	UNIQUE (provider_name, provider_id),
	FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS "secret_buckets" (
	id TEXT PRIMARY KEY NOT NULL,
	user_id TEXT NOT NULL,
	scope TEXT NOT NULL CHECK (scope IN ('session', 'package', 'user')),
	binding_key TEXT NOT NULL,
	expires_at TEXT,
	created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP),
	updated_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP),
	UNIQUE(user_id, scope, binding_key)
);
CREATE TABLE IF NOT EXISTS "secret_entries" (
	bucket_id TEXT NOT NULL,
	name TEXT NOT NULL,
	description TEXT NOT NULL DEFAULT '',
	encrypted_value TEXT NOT NULL,
	allowed_hosts TEXT NOT NULL DEFAULT '[]',
	allowed_capabilities TEXT NOT NULL DEFAULT '[]',
	lookup_hash TEXT,
	allowed_packages TEXT NOT NULL DEFAULT '[]',
	created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP),
	updated_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP),
	PRIMARY KEY (bucket_id, name),
	FOREIGN KEY (bucket_id) REFERENCES "secret_buckets"(id) ON DELETE CASCADE
);
CREATE TABLE feature_flags (
	key TEXT PRIMARY KEY NOT NULL,
	enabled INTEGER NOT NULL DEFAULT 0 CHECK (enabled IN (0, 1)),
	rollout_percent INTEGER CHECK (rollout_percent BETWEEN 0 AND 100),
	note TEXT NOT NULL DEFAULT '',
	updated_by INTEGER REFERENCES users(id) ON DELETE SET NULL,
	updated_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP)
);
CREATE TABLE feature_flag_user_overrides (
	flag_key TEXT NOT NULL,
	user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
	enabled INTEGER NOT NULL CHECK (enabled IN (0, 1)),
	updated_by INTEGER REFERENCES users(id) ON DELETE SET NULL,
	updated_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP),
	PRIMARY KEY (flag_key, user_id)
);
CREATE TABLE user_follows (
	follower_user_id TEXT NOT NULL,
	followee_user_id TEXT NOT NULL,
	created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP),
	PRIMARY KEY (follower_user_id, followee_user_id)
);
CREATE TABLE community_stars (
	listing_id TEXT NOT NULL,
	user_id TEXT NOT NULL,
	created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP),
	PRIMARY KEY (listing_id, user_id)
);
CREATE TABLE community_activity_events (
	id TEXT PRIMARY KEY NOT NULL,
	actor_user_id TEXT NOT NULL,
	event_type TEXT NOT NULL CHECK (event_type IN ('listing_published', 'listing_updated')),
	listing_id TEXT NOT NULL,
	created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP)
);
CREATE TABLE IF NOT EXISTS "community_forks" (
	id TEXT PRIMARY KEY NOT NULL,
	listing_id TEXT NOT NULL,
	forker_user_id TEXT NOT NULL,
	origin_commit TEXT NOT NULL,
	forked_package_id TEXT NOT NULL,
	forked_source_id TEXT NOT NULL,
	target_kody_id TEXT NOT NULL,
	listing_name TEXT,
	listing_kody_id TEXT,
	created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP)
, adopted_at TEXT, adoption_note TEXT, actor TEXT
CHECK (actor IS NULL OR actor IN ('human', 'agent')));
CREATE TABLE package_scope_grants (
	scope_owner_user_id TEXT NOT NULL,
	grantee_user_id TEXT NOT NULL,
	created_by_user_id TEXT NOT NULL,
	created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP),
	PRIMARY KEY (scope_owner_user_id, grantee_user_id),
	CHECK (scope_owner_user_id != grantee_user_id)
);
CREATE TABLE agent_package_conversation_uses (
	user_id TEXT NOT NULL,
	package_id TEXT NOT NULL,
	conversation_id TEXT NOT NULL,
	first_used_at TEXT NOT NULL,
	last_used_at TEXT NOT NULL,
	PRIMARY KEY (user_id, package_id, conversation_id)
);
CREATE TABLE IF NOT EXISTS "email_sender_identities" (
	id TEXT PRIMARY KEY,
	user_id TEXT NOT NULL,
	package_id TEXT,
	email TEXT NOT NULL,
	domain TEXT,
	display_name TEXT NOT NULL DEFAULT '',
	status TEXT NOT NULL CHECK (status IN ('verified')),
	verified_at TEXT,
	created_at TEXT NOT NULL,
	updated_at TEXT NOT NULL
);
CREATE TABLE mcp_agent_sessions (
	do_id TEXT PRIMARY KEY NOT NULL,
	user_id TEXT NOT NULL,
	created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP)
);
CREATE TABLE account_write_lease_repairs (
	id TEXT PRIMARY KEY NOT NULL,
	target_user_id TEXT NOT NULL,
	lease_token TEXT NOT NULL,
	lease_holder TEXT NOT NULL,
	lease_acquired_at TEXT NOT NULL,
	repaired_by_user_id TEXT NOT NULL,
	reason TEXT NOT NULL,
	created_at TEXT NOT NULL
);
CREATE TABLE webhook_endpoints (
	id TEXT PRIMARY KEY,
	user_id TEXT NOT NULL,
	package_id TEXT NOT NULL,
	webhook_name TEXT NOT NULL,
	url_secret_hash TEXT NOT NULL,
	enabled INTEGER NOT NULL DEFAULT 1 CHECK (enabled IN (0, 1)),
	created_at TEXT NOT NULL,
	rotated_at TEXT NOT NULL
);
CREATE TABLE stripe_webhook_events (
	event_id TEXT PRIMARY KEY NOT NULL,
	event_type TEXT NOT NULL,
	processed_at TEXT NOT NULL
);
CREATE TABLE package_service_states (
	user_id TEXT NOT NULL,
	package_id TEXT NOT NULL,
	service_name TEXT NOT NULL,
	status TEXT NOT NULL CHECK (status IN ('running', 'idle', 'stopped', 'error')),
	started_at TEXT,
	updated_at TEXT NOT NULL,
	PRIMARY KEY (user_id, package_id, service_name)
);
CREATE TABLE user_oauth_apps (
	user_id TEXT NOT NULL,
	slug TEXT NOT NULL,
	provider TEXT NOT NULL,
	label TEXT,
	client_id TEXT NOT NULL,
	client_secret_secret_name TEXT,
	token_url TEXT NOT NULL,
	authorize_url TEXT,
	api_base_url TEXT,
	flow TEXT NOT NULL CHECK (flow IN ('pkce', 'confidential')),
	use_pkce INTEGER CHECK (use_pkce IN (0, 1)),
	token_exchange_style TEXT CHECK (token_exchange_style IN ('form', 'basic-json', 'basic-form')),
	scope_separator TEXT,
	extra_authorize_params_json TEXT NOT NULL DEFAULT '{}',
	created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ', 'now')),
	updated_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ', 'now')),
	PRIMARY KEY (user_id, slug)
);
CREATE TABLE user_integrations (
	user_id TEXT NOT NULL,
	name TEXT NOT NULL,
	app_slug TEXT NOT NULL,
	account_label TEXT,
	description TEXT NOT NULL DEFAULT '',
	scopes_json TEXT NOT NULL DEFAULT '[]',
	required_hosts_json TEXT NOT NULL DEFAULT '[]',
	access_token_secret_name TEXT NOT NULL,
	refresh_token_secret_name TEXT,
	connected_at TEXT,
	token_refreshed_at TEXT,
	created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ', 'now')),
	updated_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ', 'now')),
	PRIMARY KEY (user_id, name),
	FOREIGN KEY (user_id, app_slug) REFERENCES user_oauth_apps(user_id, slug) ON DELETE RESTRICT
);
CREATE TABLE user_openapi_bindings (
	user_id TEXT NOT NULL,
	name TEXT NOT NULL,
	spec_url TEXT NOT NULL,
	api_base_url TEXT NOT NULL,
	description TEXT,
	auth_json TEXT NOT NULL,
	selection_json TEXT NOT NULL,
	include_destructive INTEGER NOT NULL DEFAULT 0 CHECK (include_destructive IN (0, 1)),
	spec_title TEXT,
	spec_version TEXT,
	created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ', 'now')),
	updated_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ', 'now')),
	PRIMARY KEY (user_id, name)
);
CREATE TABLE user_openapi_binding_operations (
	user_id TEXT NOT NULL,
	binding_name TEXT NOT NULL,
	slug TEXT NOT NULL,
	operation_json TEXT NOT NULL,
	PRIMARY KEY (user_id, binding_name, slug),
	FOREIGN KEY (user_id, binding_name) REFERENCES user_openapi_bindings(user_id, name) ON DELETE CASCADE
);
CREATE TABLE email_sender_rules (
	id TEXT PRIMARY KEY,
	user_id TEXT NOT NULL,
	kind TEXT NOT NULL CHECK (kind IN ('address', 'domain')),
	value TEXT NOT NULL,
	effect TEXT NOT NULL CHECK (effect IN ('allow', 'block', 'quarantine')),
	note TEXT NOT NULL DEFAULT '',
	created_at TEXT NOT NULL,
	updated_at TEXT NOT NULL
);
CREATE TABLE package_codemod_runs (
	id TEXT PRIMARY KEY NOT NULL,
	codemod_id TEXT NOT NULL,
	mode TEXT NOT NULL,
	scope_user_id TEXT,
	initiated_by_user_id TEXT NOT NULL,
	filters_json TEXT NOT NULL DEFAULT '{}',
	status TEXT NOT NULL,
	revert_of_run_id TEXT,
	created_at TEXT NOT NULL,
	updated_at TEXT NOT NULL
);
CREATE TABLE package_codemod_run_items (
	id TEXT PRIMARY KEY NOT NULL,
	run_id TEXT NOT NULL,
	user_id TEXT NOT NULL,
	package_id TEXT NOT NULL,
	kody_id TEXT NOT NULL,
	status TEXT NOT NULL,
	before_commit TEXT,
	after_commit TEXT,
	changed_paths_json TEXT NOT NULL DEFAULT '[]',
	findings_json TEXT NOT NULL DEFAULT '[]',
	check_summary_json TEXT,
	error TEXT,
	revert_snapshot_key TEXT,
	created_at TEXT NOT NULL,
	updated_at TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS "invites" (
	code TEXT PRIMARY KEY NOT NULL,
	created_by INTEGER,
	note TEXT NOT NULL DEFAULT '',
	max_uses INTEGER NOT NULL DEFAULT 1 CHECK (max_uses > 0),
	use_count INTEGER NOT NULL DEFAULT 0 CHECK (use_count >= 0),
	expires_at TEXT,
	revoked_at TEXT,
	created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP),
	plan TEXT NOT NULL DEFAULT 'free' CHECK (
		plan IN ('free', 'partner', 'pro', 'max')
	),
	FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL
);
CREATE TABLE IF NOT EXISTS "platform_feedback" (
	id TEXT PRIMARY KEY NOT NULL,
	submitter_user_id TEXT NOT NULL,
	category TEXT NOT NULL CHECK (
		category IN ('friction', 'bug', 'experience', 'suggestion', 'other')
	),
	summary TEXT NOT NULL CHECK (
		length(summary) BETWEEN 1 AND 200
	),
	details TEXT NOT NULL CHECK (
		length(details) BETWEEN 1 AND 8000
	),
	status TEXT NOT NULL DEFAULT 'open' CHECK (
		status IN ('open', 'triaged', 'resolved', 'dismissed')
	),
	reviewed_by_user_id TEXT,
	reviewed_at TEXT,
	admin_note TEXT CHECK (
		admin_note IS NULL OR length(admin_note) <= 2000
	),
	revision INTEGER NOT NULL DEFAULT 0,
	created_at TEXT NOT NULL,
	updated_at TEXT NOT NULL,
	submitter_username TEXT NOT NULL,
	submitter_email TEXT NOT NULL
);
CREATE TABLE feature_flag_exposure_rollups (
	flag_key TEXT NOT NULL,
	user_id TEXT NOT NULL,
	day TEXT NOT NULL,
	enabled INTEGER NOT NULL CHECK (enabled IN (0, 1)),
	source TEXT NOT NULL,
	exposure_count INTEGER NOT NULL DEFAULT 0,
	updated_at TEXT NOT NULL,
	PRIMARY KEY (flag_key, user_id, day, enabled, source)
);
CREATE TABLE IF NOT EXISTS "user_storage_buckets" (
	user_id TEXT NOT NULL,
	storage_id TEXT NOT NULL,
	kind TEXT NOT NULL CHECK (
		kind IN ('job', 'package', 'service', 'execute', 'unknown')
	),
	created_at TEXT NOT NULL,
	last_seen_at TEXT NOT NULL,
	estimated_bytes INTEGER,
	estimated_bytes_updated_at TEXT,
	PRIMARY KEY (user_id, storage_id)
);
CREATE TABLE system_email_threads (
	id TEXT PRIMARY KEY,
	inbox_id TEXT,
	subject_normalized TEXT NOT NULL DEFAULT '',
	root_message_id_header TEXT,
	last_message_at TEXT NOT NULL,
	created_at TEXT NOT NULL,
	updated_at TEXT NOT NULL,
	FOREIGN KEY (inbox_id) REFERENCES email_inboxes(id) ON DELETE SET NULL
);
CREATE TABLE system_email_messages (
	id TEXT PRIMARY KEY,
	direction TEXT NOT NULL CHECK (direction IN ('inbound', 'outbound')),
	inbox_id TEXT,
	thread_id TEXT,
	sender_identity_id TEXT,
	from_address TEXT NOT NULL,
	envelope_from TEXT,
	to_addresses_json TEXT NOT NULL DEFAULT '[]',
	cc_addresses_json TEXT NOT NULL DEFAULT '[]',
	bcc_addresses_json TEXT NOT NULL DEFAULT '[]',
	reply_to_addresses_json TEXT NOT NULL DEFAULT '[]',
	subject TEXT NOT NULL DEFAULT '',
	message_id_header TEXT,
	in_reply_to_header TEXT,
	references_json TEXT NOT NULL DEFAULT '[]',
	headers_json TEXT NOT NULL DEFAULT '{}',
	auth_results TEXT,
	text_body TEXT,
	html_body TEXT,
	raw_size INTEGER NOT NULL DEFAULT 0,
	processing_status TEXT NOT NULL CHECK (
		processing_status IN ('stored', 'sent', 'failed')
	),
	provider_message_id TEXT,
	error TEXT,
	received_at TEXT,
	sent_at TEXT,
	created_at TEXT NOT NULL,
	updated_at TEXT NOT NULL,
	raw_mime_key TEXT,
	delivery_status TEXT CHECK (
		delivery_status IS NULL
		OR delivery_status IN (
			'delivered', 'deferred', 'bounced', 'failed', 'rejected', 'complained'
		)
	),
	delivery_status_at TEXT,
	classification TEXT NOT NULL DEFAULT 'accepted'
		CHECK (classification IN ('accepted', 'quarantined')),
	classification_reason TEXT,
	FOREIGN KEY (inbox_id) REFERENCES email_inboxes(id) ON DELETE SET NULL,
	FOREIGN KEY (thread_id) REFERENCES system_email_threads(id) ON DELETE SET NULL,
	FOREIGN KEY (sender_identity_id) REFERENCES email_sender_identities(id)
		ON DELETE SET NULL
);
CREATE TABLE system_email_attachments (
	id TEXT PRIMARY KEY,
	message_id TEXT NOT NULL,
	filename TEXT,
	content_type TEXT NOT NULL,
	content_id TEXT,
	disposition TEXT,
	size INTEGER NOT NULL DEFAULT 0,
	storage_kind TEXT NOT NULL CHECK (
		storage_kind IN ('raw-mime', 'external', 'unavailable')
	),
	storage_key TEXT,
	created_at TEXT NOT NULL,
	FOREIGN KEY (message_id) REFERENCES system_email_messages(id)
		ON DELETE CASCADE
);
CREATE TABLE system_email_delivery_events (
	id TEXT PRIMARY KEY,
	message_id TEXT,
	inbox_id TEXT,
	event_type TEXT NOT NULL CHECK (
		event_type IN (
			'receive_started', 'received', 'rejected', 'send_requested', 'sent',
			'failed', 'delivered', 'deferred', 'bounced', 'complained'
		)
	),
	provider TEXT NOT NULL DEFAULT 'kody',
	provider_message_id TEXT,
	provider_event_id TEXT,
	detail_json TEXT NOT NULL DEFAULT '{}',
	created_at TEXT NOT NULL,
	needs_effect_reconcile INTEGER NOT NULL DEFAULT 1
		CHECK (needs_effect_reconcile IN (0, 1)),
	usage_effect_recorded_at TEXT,
	usage_month TEXT,
	usage_bytes INTEGER,
	usage_duration_ms INTEGER,
	state TEXT CHECK (
		state IS NULL
		OR state IN (
			'pending', 'storing', 'cleaning', 'received', 'rejected',
			'orphan-cleaned'
		)
	),
	fingerprint TEXT,
	storage_lease TEXT,
	storage_lease_at TEXT,
	cleanup_lease TEXT,
	cleanup_lease_at TEXT,
	cleanup_retry_at TEXT,
	expected_attachment_count INTEGER,
	finalization_token TEXT,
	reconcile_after TEXT,
	dedupe_expires_at TEXT,
	usage_effect_suppressed_at TEXT,
	usage_started_at TEXT,
	usage_effect_retry_at TEXT,
	usage_effect_lease TEXT,
	usage_effect_lease_at TEXT,
	subscription_effect_state TEXT CHECK (
		subscription_effect_state IS NULL
		OR subscription_effect_state IN (
			'pending', 'processing', 'complete', 'dead-letter'
		)
	),
	subscription_effect_lease TEXT,
	subscription_effect_lease_at TEXT,
	subscription_effect_retry_at TEXT,
	subscription_effect_attempt_count INTEGER,
	subscription_effect_dead_letter_at TEXT,
	subscription_effect_last_error TEXT,
	updated_at TEXT,
	FOREIGN KEY (message_id) REFERENCES system_email_messages(id)
		ON DELETE SET NULL,
	FOREIGN KEY (inbox_id) REFERENCES email_inboxes(id) ON DELETE SET NULL
);
CREATE TABLE system_email_graph_authority (
	singleton INTEGER PRIMARY KEY CHECK (singleton = 1),
	authority TEXT NOT NULL CHECK (authority = 'dedicated'),
	cutover_at TEXT NOT NULL,
	graph_mismatch_count INTEGER NOT NULL CHECK (graph_mismatch_count = 0),
	provider_link_count INTEGER NOT NULL CHECK (provider_link_count = 0)
);
INSERT INTO system_email_graph_authority VALUES(1,'dedicated','2026-08-04 20:55:37',0,0);
CREATE TABLE IF NOT EXISTS "email_outbound_provider_index" (
	provider TEXT NOT NULL,
	provider_message_id TEXT NOT NULL,
	user_id TEXT NOT NULL CHECK (user_id <> 'system:email'),
	message_id TEXT NOT NULL,
	inbox_id TEXT,
	created_at TEXT NOT NULL,
	updated_at TEXT NOT NULL,
	PRIMARY KEY (provider, provider_message_id)
);
CREATE TABLE email_inbound_due_owners (
	user_id TEXT PRIMARY KEY NOT NULL CHECK (user_id != 'system:email'),
	due_at TEXT NOT NULL,
	reason TEXT NOT NULL,
	attempt_count INTEGER NOT NULL DEFAULT 0 CHECK (attempt_count >= 0),
	last_error TEXT,
	updated_at TEXT NOT NULL
);
CREATE TABLE email_outbound_provider_index_repair_owners (
	user_id TEXT PRIMARY KEY NOT NULL CHECK (user_id != 'system:email'),
	pending_count INTEGER NOT NULL CHECK (pending_count > 0),
	oldest_pending_at TEXT NOT NULL,
	updated_at TEXT NOT NULL
);
CREATE TABLE email_delivery_alert_events (
	provider_event_id TEXT PRIMARY KEY NOT NULL,
	provider TEXT NOT NULL,
	event_type TEXT NOT NULL CHECK (event_type IN ('bounced', 'complained')),
	occurred_at TEXT NOT NULL,
	owner_hash TEXT,
	created_at TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS "email_user_graph_authority" (
	singleton INTEGER PRIMARY KEY NOT NULL CHECK (singleton = 1),
	owner_count INTEGER NOT NULL CHECK (owner_count >= 0),
	frozen_at TEXT NOT NULL,
	dropped_at TEXT NOT NULL
);
INSERT INTO email_user_graph_authority VALUES(1,0,'2026-08-04T20:55:38.184Z','2026-08-04T20:55:39.233Z');
CREATE TABLE IF NOT EXISTS "users" (
	id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
	username TEXT NOT NULL UNIQUE,
	email TEXT NOT NULL UNIQUE,
	password_hash TEXT NOT NULL,
	created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP),
	updated_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP),
	email_verified_at TEXT,
	plan TEXT NOT NULL DEFAULT 'free' CHECK (
		plan IN ('free', 'partner', 'pro', 'max')
	),
	stable_user_id TEXT NOT NULL,
	stripe_customer_id TEXT,
	stripe_plan TEXT,
	stripe_plan_refreshed_at TEXT,
	display_name TEXT,
	bio TEXT,
	profile_visibility TEXT NOT NULL DEFAULT 'public' CHECK (
		profile_visibility IN ('public', 'private')
	),
	avatar_key TEXT,
	account_type TEXT NOT NULL DEFAULT 'person' CHECK (
		account_type IN ('person', 'platform')
	),
	deleting_at TEXT,
	active_write_count INTEGER NOT NULL DEFAULT 0,
	active_write_expires_at TEXT,
	suspended_at TEXT,
	email_outbound_paused_at TEXT,
	password_changed_at TEXT,
	job_retention_success_once_days INTEGER CHECK (
		job_retention_success_once_days IS NULL
		OR (
			job_retention_success_once_days >= 1
			AND job_retention_success_once_days <= 365
		)
	),
	job_retention_failed_once_days INTEGER CHECK (
		job_retention_failed_once_days IS NULL
		OR (
			job_retention_failed_once_days >= 1
			AND job_retention_failed_once_days <= 365
		)
	),
	job_retention_disabled_recurring_days INTEGER CHECK (
		job_retention_disabled_recurring_days IS NULL
		OR (
			job_retention_disabled_recurring_days >= 1
			AND job_retention_disabled_recurring_days <= 365
		)
	));
CREATE TABLE user_repos (
	id TEXT PRIMARY KEY NOT NULL,
	user_id TEXT NOT NULL,
	name TEXT NOT NULL,
	description TEXT NULL,
	created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP),
	updated_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP)
);
CREATE TABLE entity_source_artifacts_push_subscriptions (
	source_id TEXT PRIMARY KEY NOT NULL,
	user_id TEXT NOT NULL,
	repo_id TEXT NOT NULL,
	subscription_id TEXT NOT NULL,
	created_at TEXT NOT NULL,
	updated_at TEXT NOT NULL
);
CREATE TABLE d1_storage_reconcile_cursor (
	singleton INTEGER PRIMARY KEY NOT NULL CHECK (singleton = 1),
	position TEXT NOT NULL DEFAULT '',
	updated_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP)
);
INSERT INTO d1_storage_reconcile_cursor VALUES(1,'','2026-08-04 20:55:39');
CREATE INDEX idx_password_resets_user_id ON password_resets(user_id);
CREATE INDEX idx_password_resets_token_hash ON password_resets(token_hash);
CREATE INDEX idx_value_buckets_user_scope_binding
	ON value_buckets(user_id, scope, binding_key);
CREATE INDEX idx_value_entries_bucket_id
	ON value_entries(bucket_id);
CREATE INDEX idx_value_entries_name
	ON value_entries(name);
CREATE INDEX idx_mcp_memories_user_status_updated
	ON mcp_memories(user_id, status, updated_at);
CREATE INDEX idx_mcp_memories_user_category_status
	ON mcp_memories(user_id, category, status);
CREATE INDEX idx_mcp_memories_user_dedupe_key
	ON mcp_memories(user_id, dedupe_key);
CREATE INDEX idx_mcp_memory_suppressions_expires_at
	ON mcp_memory_conversation_suppressions(expires_at);
CREATE UNIQUE INDEX idx_entity_sources_user_entity
ON entity_sources(user_id, entity_kind, entity_id);
CREATE UNIQUE INDEX idx_entity_sources_repo_id
ON entity_sources(repo_id);
CREATE INDEX idx_entity_sources_user_id
ON entity_sources(user_id);
CREATE INDEX idx_jobs_user_next_run_at
	ON jobs(user_id, enabled, kill_switch_enabled, next_run_at);
CREATE INDEX idx_jobs_user_name
	ON jobs(user_id, name);
CREATE INDEX idx_jobs_source_id
	ON jobs(source_id);
CREATE UNIQUE INDEX idx_saved_packages_user_kody_id
ON saved_packages(user_id, kody_id);
CREATE UNIQUE INDEX idx_saved_packages_user_name
ON saved_packages(user_id, name);
CREATE UNIQUE INDEX idx_saved_packages_source_id
ON saved_packages(source_id);
CREATE UNIQUE INDEX idx_published_bundle_artifacts_source_identity
ON published_bundle_artifacts(
	user_id,
	source_id,
	artifact_kind,
	COALESCE(artifact_name, ''),
	entry_point
);
CREATE INDEX idx_published_bundle_artifacts_user_id
ON published_bundle_artifacts(user_id);
CREATE INDEX idx_published_bundle_artifacts_source_id
ON published_bundle_artifacts(source_id);
CREATE INDEX idx_archived_job_artifacts_user_id
ON archived_job_artifacts(user_id);
CREATE INDEX idx_archived_job_artifacts_retain_until
ON archived_job_artifacts(retain_until);
CREATE INDEX idx_package_invocation_tokens_user_id
ON package_invocation_tokens(user_id);
CREATE INDEX idx_package_invocation_tokens_token_hash
ON package_invocation_tokens(token_hash);
CREATE UNIQUE INDEX idx_email_inboxes_user_name
ON email_inboxes(user_id, name);
CREATE INDEX idx_email_inboxes_user_created_at
ON email_inboxes(user_id, created_at);
CREATE UNIQUE INDEX idx_email_inbox_addresses_address
ON email_inbox_addresses(address);
CREATE INDEX idx_email_inbox_addresses_inbox_id
ON email_inbox_addresses(inbox_id);
CREATE INDEX idx_entity_sources_external_check
	ON entity_sources(last_external_check_at);
CREATE INDEX idx_repo_sessions_user_id
ON repo_sessions(user_id);
CREATE INDEX idx_repo_sessions_source_id
ON repo_sessions(source_id);
CREATE INDEX idx_repo_sessions_conversation_id
ON repo_sessions(conversation_id);
CREATE INDEX idx_repo_sessions_cleanup
ON repo_sessions(status, expires_at, updated_at);
CREATE INDEX idx_user_roles_user_id ON user_roles(user_id);
CREATE UNIQUE INDEX idx_community_listings_owner_package
ON community_listings(owner_user_id, package_id);
CREATE INDEX idx_community_listings_status
ON community_listings(status);
CREATE UNIQUE INDEX idx_community_ratings_listing_user
ON community_ratings(listing_id, user_id);
CREATE INDEX idx_community_reports_status
ON community_reports(status);
CREATE INDEX idx_email_verifications_user_id ON email_verifications(user_id);
CREATE INDEX idx_email_verifications_token_hash ON email_verifications(token_hash);
CREATE INDEX idx_usage_rollups_user_month
ON usage_rollups(user_id, month);
CREATE INDEX idx_remote_connector_settings_ref_enabled
	ON remote_connector_settings(instance_id, enabled);
CREATE INDEX idx_pending_email_changes_user_id
	ON pending_email_changes(user_id);
CREATE UNIQUE INDEX idx_pending_email_changes_new_email
	ON pending_email_changes(new_email);
CREATE INDEX idx_pending_email_changes_token_hash
	ON pending_email_changes(token_hash);
CREATE INDEX idx_mcp_server_settings_user_enabled
	ON mcp_server_settings(user_id, enabled);
CREATE INDEX idx_verifications_target_type ON verifications(target, type);
CREATE INDEX idx_passkeys_user_id ON passkeys(user_id);
CREATE INDEX idx_usage_rollups_month
ON usage_rollups(month);
CREATE INDEX idx_published_bundle_artifacts_created_at
ON published_bundle_artifacts(created_at);
CREATE INDEX idx_oauth_connections_user_id ON oauth_connections(user_id);
CREATE INDEX idx_secret_buckets_user_scope_binding
	ON secret_buckets(user_id, scope, binding_key);
CREATE INDEX idx_secret_entries_bucket_id
	ON secret_entries(bucket_id);
CREATE INDEX idx_secret_entries_name
	ON secret_entries(name);
CREATE INDEX idx_secret_entries_lookup_hash
	ON secret_entries(lookup_hash);
CREATE INDEX idx_feature_flag_user_overrides_user_id
ON feature_flag_user_overrides(user_id);
CREATE INDEX idx_user_follows_followee_user_id
ON user_follows(followee_user_id);
CREATE INDEX idx_community_stars_user_id
ON community_stars(user_id);
CREATE INDEX idx_community_activity_events_actor_created
ON community_activity_events(actor_user_id, created_at);
CREATE INDEX idx_community_activity_events_listing_id
ON community_activity_events(listing_id);
CREATE INDEX idx_community_forks_listing_id
	ON community_forks(listing_id);
CREATE INDEX idx_community_forks_forker_listing
	ON community_forks(forker_user_id, listing_id);
CREATE INDEX idx_package_scope_grants_grantee_user_id
ON package_scope_grants(grantee_user_id);
CREATE INDEX idx_agent_package_conversation_uses_user_last_used
ON agent_package_conversation_uses(user_id, last_used_at);
CREATE INDEX idx_community_forks_forked_package_id
ON community_forks(forked_package_id);
CREATE UNIQUE INDEX idx_email_sender_identities_user_email
ON email_sender_identities(user_id, email);
CREATE INDEX idx_email_sender_identities_user_domain
ON email_sender_identities(user_id, domain);
CREATE INDEX idx_mcp_agent_sessions_user_id
ON mcp_agent_sessions(user_id);
CREATE UNIQUE INDEX idx_webhook_endpoints_user_package_name
ON webhook_endpoints(user_id, package_id, webhook_name);
CREATE INDEX idx_webhook_endpoints_user_created_at
ON webhook_endpoints(user_id, created_at);
CREATE INDEX idx_stripe_webhook_events_processed_at
ON stripe_webhook_events(processed_at);
CREATE INDEX idx_package_service_states_user_status
ON package_service_states(user_id, status);
CREATE INDEX idx_jobs_retention_candidates
	ON jobs(preserved, enabled, last_run_at, updated_at);
CREATE INDEX idx_user_integrations_user_app_slug
ON user_integrations(user_id, app_slug);
CREATE INDEX idx_user_oauth_apps_user_provider
ON user_oauth_apps(user_id, provider);
CREATE UNIQUE INDEX idx_email_sender_rules_user_kind_value
	ON email_sender_rules(user_id, kind, value);
CREATE INDEX idx_package_codemod_run_items_run_id
ON package_codemod_run_items(run_id);
CREATE INDEX idx_package_codemod_runs_codemod_created
ON package_codemod_runs(codemod_id, created_at);
CREATE INDEX idx_invites_created_at ON invites(created_at);
CREATE INDEX idx_invites_created_by ON invites(created_by);
CREATE INDEX idx_invites_expires_at ON invites(expires_at);
CREATE INDEX idx_platform_feedback_created_at_id
ON platform_feedback(created_at DESC, id DESC);
CREATE INDEX idx_platform_feedback_status_created_at_id
ON platform_feedback(status, created_at DESC, id DESC);
CREATE INDEX idx_platform_feedback_category_created_at_id
ON platform_feedback(category, created_at DESC, id DESC);
CREATE INDEX idx_platform_feedback_reviewer
ON platform_feedback(reviewed_by_user_id);
CREATE INDEX idx_platform_feedback_submitter_status
ON platform_feedback(submitter_user_id, status);
CREATE INDEX idx_platform_feedback_submitter_created_at
ON platform_feedback(submitter_user_id, created_at);
CREATE INDEX idx_platform_feedback_terminal_updated_at_id
ON platform_feedback(updated_at, id)
WHERE status IN ('resolved', 'dismissed');
CREATE INDEX idx_jobs_user_enabled_expires_next_run
	ON jobs(user_id, enabled, kill_switch_enabled, expires_at, next_run_at);
CREATE INDEX idx_feature_flag_exposure_rollups_user_id
	ON feature_flag_exposure_rollups (user_id);
CREATE INDEX idx_feature_flag_exposure_rollups_day
	ON feature_flag_exposure_rollups (day);
CREATE INDEX idx_user_storage_buckets_user
ON user_storage_buckets(user_id);
CREATE INDEX idx_entity_sources_pending_external_reconcile
ON entity_sources(external_check_until, last_external_check_at, id)
WHERE entity_kind = 'package' AND external_check_until IS NOT NULL;
CREATE INDEX idx_system_email_threads_last_message_at
ON system_email_threads(last_message_at);
CREATE INDEX idx_system_email_threads_root_message_id
ON system_email_threads(root_message_id_header);
CREATE INDEX idx_system_email_messages_created_at
ON system_email_messages(created_at);
CREATE INDEX idx_system_email_messages_inbox_created_at
ON system_email_messages(inbox_id, created_at);
CREATE INDEX idx_system_email_messages_thread_created_at
ON system_email_messages(thread_id, created_at);
CREATE INDEX idx_system_email_messages_message_id_header
ON system_email_messages(message_id_header);
CREATE UNIQUE INDEX idx_system_email_messages_provider_message_id
ON system_email_messages(provider_message_id)
WHERE direction = 'outbound' AND provider_message_id IS NOT NULL;
CREATE INDEX idx_system_email_messages_quarantined_created_at
ON system_email_messages(created_at)
WHERE classification = 'quarantined';
CREATE INDEX idx_system_email_attachments_message_id
ON system_email_attachments(message_id);
CREATE INDEX idx_system_email_delivery_events_message_id
ON system_email_delivery_events(message_id);
CREATE INDEX idx_system_email_delivery_events_created_at
ON system_email_delivery_events(created_at);
CREATE UNIQUE INDEX idx_system_email_delivery_events_provider_event_id
ON system_email_delivery_events(provider_event_id)
WHERE provider_event_id IS NOT NULL;
CREATE INDEX idx_system_email_delivery_events_provider_event_created
ON system_email_delivery_events(provider, event_type, created_at);
CREATE INDEX idx_system_email_delivery_events_pending_effects
ON system_email_delivery_events(created_at)
WHERE provider = 'cloudflare-email-routing'
	AND event_type = 'received'
	AND needs_effect_reconcile = 1;
CREATE INDEX idx_system_email_delivery_events_recorded_usage_month
ON system_email_delivery_events(usage_month)
WHERE provider = 'cloudflare-email-routing'
	AND event_type = 'received'
	AND usage_effect_recorded_at IS NOT NULL;
CREATE INDEX idx_system_email_delivery_events_state_created
ON system_email_delivery_events(state, created_at, id)
WHERE provider = 'cloudflare-email-routing' AND state IS NOT NULL;
CREATE INDEX idx_system_email_delivery_events_dedupe_expires
ON system_email_delivery_events(dedupe_expires_at, id)
WHERE provider = 'cloudflare-email-routing-dedupe'
	AND dedupe_expires_at IS NOT NULL;
CREATE INDEX idx_email_outbound_provider_index_user_id
	ON email_outbound_provider_index(user_id);
CREATE UNIQUE INDEX idx_email_outbound_provider_index_message_id
	ON email_outbound_provider_index(message_id);
CREATE INDEX idx_email_outbound_provider_index_repair_owners_oldest
	ON email_outbound_provider_index_repair_owners(oldest_pending_at, user_id);
CREATE INDEX idx_email_delivery_alert_events_occurred_at
	ON email_delivery_alert_events(occurred_at, provider_event_id);
CREATE INDEX idx_users_username ON users(username);
CREATE INDEX idx_users_email ON users(email);
CREATE UNIQUE INDEX idx_users_stable_user_id
	ON users(stable_user_id);
CREATE UNIQUE INDEX idx_users_stripe_customer_id
	ON users(stripe_customer_id)
	WHERE stripe_customer_id IS NOT NULL;
CREATE INDEX idx_users_deleting_at
	ON users(deleting_at)
	WHERE deleting_at IS NOT NULL;
CREATE UNIQUE INDEX idx_user_repos_user_name ON user_repos(user_id, name);
CREATE UNIQUE INDEX idx_entity_source_artifacts_push_subscriptions_repo_id
	ON entity_source_artifacts_push_subscriptions(repo_id);
CREATE INDEX idx_email_inbound_due_owners_priority_due_at
	ON email_inbound_due_owners(due_at, user_id);
