/**
 * Built-in provider keys and authorize hosts for marks we must resolve even
 * when the operator catalog row is missing an alias. Family matching still
 * covers `{slug}-*` / `*-{slug}`; this table is the exact keys and hosts.
 */
export const defaultProviderMarkAliases = {
	airtable: ['api.airtable.com'],
	anthropic: ['claude', 'api.anthropic.com'],
	asana: ['app.asana.com'],
	atlassian: ['id.atlassian.com', 'auth.atlassian.com', 'api.atlassian.com'],
	aws: [
		'amazon',
		'amazonaws',
		'sts.amazonaws.com',
		's3.amazonaws.com',
		'amazonwebservices',
	],
	bluesky: ['bsky', 'bsky.social', 'bsky.app'],
	box: ['account.box.com', 'api.box.com'],
	brave: ['api.search.brave.com', 'bravesearch', 'brave-search'],
	'cal-com': ['caldotcom', 'cal.com', 'app.cal.com', 'api.cal.com'],
	calendly: ['auth.calendly.com', 'api.calendly.com'],
	canva: ['www.canva.com', 'api.canva.com'],
	clerk: ['clerk.dev', 'clerk.com'],
	cloudflare: ['dash.cloudflare.com', 'api.cloudflare.com'],
	cockroachlabs: ['cockroachdb', 'cockroach'],
	cursor: ['cursor.com', 'api2.cursor.sh'],
	datadog: ['app.datadoghq.com', 'api.datadoghq.com'],
	devin: ['app.devin.ai', 'devin.ai', 'cognition'],
	discord: ['discord.com', 'discordapp.com', 'discord.gg'],
	dropbox: ['www.dropbox.com', 'api.dropboxapi.com', 'content.dropboxapi.com'],
	drizzle: ['drizzle-orm'],
	duckduckgo: ['duckduckgo.com'],
	facebook: ['www.facebook.com', 'graph.facebook.com'],
	fathom: ['fathom-analytics', 'app.usefathom.com', 'usefathom.com'],
	figma: ['www.figma.com', 'api.figma.com'],
	firebase: ['firebase.google.com'],
	fly: ['flydotio', 'fly.io', 'api.fly.io', 'flyio'],
	github: [
		'github.com',
		'api.github.com',
		'uploads.github.com',
		'github-platform',
	],
	gitlab: ['gitlab.com'],
	gmail: ['mail.google.com', 'gmail.googleapis.com'],
	google: [
		'accounts.google.com',
		'oauth2.googleapis.com',
		'googleapis.com',
		'www.googleapis.com',
		'openidconnect.googleapis.com',
		'google-platform',
		'google-business',
	],
	'google-calendar': [
		'googlecalendar',
		'calendar.google.com',
		'calendar.googleapis.com',
	],
	'google-cloud': ['googlecloud', 'cloud.google.com'],
	'google-docs': ['googledocs', 'docs.google.com'],
	'google-drive': ['googledrive', 'drive.google.com'],
	'google-sheets': ['googlesheets', 'sheets.google.com'],
	groupme: ['oauth.groupme.com', 'api.groupme.com'],
	groq: ['api.groq.com', 'console.groq.com'],
	hubspot: ['app.hubspot.com', 'api.hubapi.com'],
	hydrawise: ['hydrawise.com', 'hunter'],
	instagram: ['www.instagram.com'],
	intercom: ['app.intercom.com', 'api.intercom.io'],
	jira: ['atlassian.net'],
	kit: ['convertkit', 'app.kit.com', 'api.convertkit.com'],
	'kody-exchange': ['kody.exchange', 'exchange.kody.codes'],
	linear: ['linear.app', 'api.linear.app'],
	linkedin: ['www.linkedin.com', 'api.linkedin.com', 'linkedin.com'],
	meta: ['www.facebook.com', 'graph.facebook.com'],
	microsoft: [
		'login.microsoftonline.com',
		'graph.microsoft.com',
		'outlook',
		'teams',
		'onedrive',
		'office',
		'microsofttodo',
	],
	neovim: ['nvim'],
	netlify: ['app.netlify.com', 'api.netlify.com'],
	nextdotjs: ['next', 'nextjs', 'next.js'],
	nodedotjs: ['node', 'nodejs', 'node.js'],
	notion: ['www.notion.so', 'api.notion.com', 'notion-platform'],
	obsidian: ['obsidian.md'],
	openai: ['api.openai.com', 'chatgpt'],
	origin: ['origin.com'],
	paypal: ['www.paypal.com', 'api.paypal.com', 'api-m.paypal.com'],
	plaid: ['production.plaid.com', 'sandbox.plaid.com', 'plaid.com'],
	planetscale: ['app.planetscale.com'],
	playwright: ['playwright.dev'],
	postgresql: ['postgres', 'psql'],
	postmark: ['api.postmarkapp.com', 'postmarkapp.com'],
	producthunt: ['www.producthunt.com', 'api.producthunt.com', 'product-hunt'],
	raycast: ['www.raycast.com'],
	reddit: ['www.reddit.com', 'oauth.reddit.com'],
	resend: ['api.resend.com', 'resend.com'],
	rollupdotjs: ['rollup', 'rollup.js'],
	rust: ['rust-lang', 'rustlang', 'www.rust-lang.org'],
	salesforce: ['force.com', 'salesforce.com'],
	sentry: ['sentry.io', 'us.sentry.io'],
	sessionize: ['sessionize.com'],
	shopify: ['myshopify.com', 'admin.shopify.com'],
	slack: ['slack.com', 'slack-platform'],
	spotify: ['accounts.spotify.com', 'api.spotify.com'],
	stripe: ['dashboard.stripe.com', 'api.stripe.com', 'connect.stripe.com'],
	supabase: ['supabase.com', 'api.supabase.com'],
	tailwindcss: ['tailwind'],
	telegram: ['oauth.telegram.org', 'api.telegram.org'],
	tesla: ['auth.tesla.com', 'fleet-auth.prd.vn.cloud.tesla.com'],
	transistor: ['transistor.fm', 'api.transistor.fm'],
	trello: ['trello.com', 'api.trello.com'],
	twilio: ['api.twilio.com'],
	twitch: ['id.twitch.tv', 'api.twitch.tv'],
	vercel: ['vercel.com', 'api.vercel.com'],
	visualstudiocode: ['vscode', 'vs-code', 'code.visualstudio.com'],
	vuedotjs: ['vue', 'vuejs', 'vue.js'],
	webassembly: ['wasm'],
	whatsapp: ['api.whatsapp.com'],
	wikipedia: ['wikipedia.org'],
	workos: ['api.workos.com', 'workos.com'],
	x: ['twitter', 'x.com', 'api.x.com', 'twitter.com', 'api.twitter.com'],
	xero: ['identity.xero.com', 'login.xero.com', 'api.xero.com'],
	ycombinator: ['hacker-news', 'hackernews', 'news.ycombinator.com', 'hn'],
	youtube: [
		'www.youtube.com',
		'youtube.googleapis.com',
		'google-youtube',
		'google-youtube-brand',
		'google-youtube-plus',
	],
	zendesk: ['zendesk.com'],
	zoom: ['zoom.us', 'api.zoom.us'],
} as const satisfies Record<string, ReadonlyArray<string>>
