export { CaseStudiesRoute } from './case-studies.tsx'
export { DiscordRoute, discordRouteLoader } from './discord.tsx'
export { FaqRoute, faqRouteLoader } from './faq.tsx'
export { PricingRoute, pricingRouteLoader } from './pricing.tsx'
export { PrivacyRoute } from './privacy.tsx'
export { SupportRoute } from './support.tsx'
export { TermsRoute } from './terms.tsx'
