import { expect, test, vi } from 'vitest'
import { McpCallerError } from '#mcp/caller-error.ts'
import { createMcpCallerContext } from '#mcp/context.ts'
import { KODY_DESCRIPTION_MAX_LENGTH } from '#worker/package-registry/types.ts'

const mockModule = vi.hoisted(() => ({
	getSavedPackageById: vi.fn(),
	resolveSavedPackageRef: vi.fn(),
	getEntitySourceByIdForUser: vi.fn(),
	markEntitySourcePendingExternalReconcile: vi.fn(),
	resolveExistingArtifactSourceRepo: vi.fn(),
	createStubSavedPackage: vi.fn(),
	resolvePackageOwnerContext: vi.fn(),
	listServerRefs: vi.fn(),
}))

vi.mock('#worker/repo/isomorphic-git-lazy.ts', () => ({
	loadIsomorphicGit: async () => ({
		git: {
			listServerRefs: (...args: Array<unknown>) =>
				mockModule.listServerRefs(...args),
		},
		http: {},
	}),
}))

vi.mock('#worker/package-registry/repo.ts', () => ({
	getSavedPackageById: (...args: Array<unknown>) =>
		mockModule.getSavedPackageById(...args),
	resolveSavedPackageRef: (...args: Array<unknown>) =>
		mockModule.resolveSavedPackageRef(...args),
}))

vi.mock('#worker/package-registry/package-owner.ts', () => ({
	packageScopeInputDescription: 'package scope',
	resolvePackageOwnerContext: (...args: Array<unknown>) =>
		mockModule.resolvePackageOwnerContext(...args),
}))

vi.mock('#worker/repo/entity-sources.ts', () => ({
	getEntitySourceByIdForUser: (...args: Array<unknown>) =>
		mockModule.getEntitySourceByIdForUser(...args),
	markEntitySourcePendingExternalReconcile: (...args: Array<unknown>) =>
		mockModule.markEntitySourcePendingExternalReconcile(...args),
}))

vi.mock('#worker/repo/artifacts.ts', async () => {
	const actual = await vi.importActual('#worker/repo/artifacts.ts')
	return {
		...(actual as object),
		resolveExistingArtifactSourceRepo: (...args: Array<unknown>) =>
			mockModule.resolveExistingArtifactSourceRepo(...args),
	}
})

vi.mock('./create-stub-package.ts', () => ({
	createStubSavedPackage: (...args: Array<unknown>) =>
		mockModule.createStubSavedPackage(...args),
}))

const { getGitRemoteCapability } = await import('./get-git-remote.ts')

const personalOwner = {
	ownerUserId: 'user-1',
	ownerScope: 'kentcdodds',
	ownerEmail: 'user-1@example.com',
	actorUserId: 'user-1',
	delegated: false,
}
const invalidInput = 'Invalid input for capability "packageGetGitRemote"'
const createRequiresLeaf =
	'`create: true` requires a package name leaf or `@scope/leaf` (without `package_id`); new package ids are generated by Kody.'

function resetMocks() {
	for (const fn of Object.values(mockModule)) fn.mockReset()
	mockModule.resolvePackageOwnerContext.mockResolvedValue(personalOwner)
}

type GitRemoteResult = {
	expires_at: string
	authenticated_remote: string
	setup_commands: Array<string>
}

async function getRemote(
	args: Record<string, unknown>,
	{ snapshot = createPublishedSnapshot() }: { snapshot?: unknown } = {},
) {
	const result = await getGitRemoteCapability.handler(args, {
		env: {
			APP_DB: {},
			BUNDLE_ARTIFACTS_KV: {
				async get(_key: string, type?: 'text' | 'json') {
					return type === 'json' ? snapshot : null
				},
			},
		} as unknown as Env,
		callerContext: createMcpCallerContext({
			baseUrl: 'https://heykody.dev',
			user: {
				userId: 'user-1',
				email: 'user-1@example.com',
				displayName: 'user-1',
			},
		}),
	})
	return result as GitRemoteResult
}

function createPublishedSnapshot() {
	return {
		version: 1,
		sourceId: 'source-1',
		repoId: 'package-package-1',
		entityKind: 'package',
		entityId: 'package-1',
		publishedCommit: 'commit-1',
		manifestPath: 'package.json',
		sourceRoot: '/',
		files: {
			'package.json': JSON.stringify({
				name: '@kentcdodds/unleashed-wifi',
				exports: { '.': './src/index.ts' },
				kody: {
					id: 'unleashed-wifi',
					description: 'Unleashed WiFi controls.',
				},
			}),
			'src/index.ts': 'export default async function main() {}\n',
		},
		createdAt: '2026-05-04T00:00:00.000Z',
	}
}

function mockPackageSource(sourceUserId = 'user-1') {
	const savedPackage = {
		id: 'package-1',
		kodyId: 'unleashed-wifi',
		name: '@kentcdodds/unleashed-wifi',
		sourceId: 'source-1',
	}
	mockModule.getSavedPackageById.mockResolvedValue(savedPackage)
	mockModule.resolveSavedPackageRef.mockResolvedValue(savedPackage)
	mockModule.getEntitySourceByIdForUser.mockImplementation(
		async (_db: unknown, input: { id: string; userId: string }) => {
			if (input.userId !== sourceUserId) return null
			return {
				id: 'source-1',
				user_id: sourceUserId,
				entity_kind: 'package',
				entity_id: 'package-1',
				repo_id: 'package-package-1',
				published_commit: 'commit-1',
				indexed_commit: null,
				manifest_path: 'package.json',
				source_root: '/',
				last_external_check_at: null,
				external_check_until: null,
				created_at: '2026-05-04T00:00:00.000Z',
				updated_at: '2026-05-04T00:00:00.000Z',
			}
		},
	)
	const createToken = vi.fn(async (scope: 'read' | 'write', ttl: number) => ({
		id: 'token-1',
		plaintext: `art_v1_${scope}_token?expires=${Math.floor(Date.now() / 1000) + ttl}`,
		scope,
		expiresAt: new Date(Date.now() + ttl * 1000).toISOString(),
	}))
	const remote =
		'https://acct.artifacts.cloudflare.net/git/default/package-package-1.git'
	mockModule.resolveExistingArtifactSourceRepo.mockResolvedValue({
		info: vi.fn(async () => ({ remote, defaultBranch: 'main' })),
		createToken,
	})
	mockModule.listServerRefs.mockResolvedValue([
		{ ref: 'refs/heads/main', oid: 'commit-1' },
	])
	return { createToken, remote }
}

function stubCreatedPackage(
	ownerUserId = 'user-1',
	name = '@kentcdodds/unleashed-wifi',
) {
	mockModule.resolveSavedPackageRef.mockResolvedValueOnce(null)
	mockModule.createStubSavedPackage.mockImplementation(async () => {
		mockPackageSource(ownerUserId)
		return { packageId: 'package-1', kodyId: 'unleashed-wifi', name }
	})
}

test('get_git_remote rejects invalid input before creating stubs', async () => {
	for (const [args, message] of [
		[{}, 'Provide exactly one of `package_id` or the package name leaf.'],
		[{ package_id: 'package-1', ttl_seconds: 59 }, invalidInput],
		[{ package_id: 'package-1', ttl_seconds: 86_401 }, invalidInput],
	] as const) {
		resetMocks()
		mockPackageSource()
		await expect(getRemote(args)).rejects.toThrow(message)
		expect(mockModule.createStubSavedPackage).not.toHaveBeenCalled()
	}

	for (const args of [
		{ package_id: 'package-1', create: true },
		{ create: true },
	] as const) {
		resetMocks()
		mockPackageSource()
		const createRequiresError = await getRemote(args).catch(
			(error: unknown) => error,
		)
		expect(createRequiresError).toBeInstanceOf(McpCallerError)
		expect(createRequiresError).toMatchObject({ message: createRequiresLeaf })
		expect(mockModule.createStubSavedPackage).not.toHaveBeenCalled()
	}

	resetMocks()
	const oversizeError = await getRemote({
		create: true,
		kody_id: 'new-package',
		description: 'a'.repeat(KODY_DESCRIPTION_MAX_LENGTH + 1),
	}).catch((error: unknown) => error)
	expect(oversizeError).toBeInstanceOf(McpCallerError)
	expect(oversizeError).toMatchObject({
		message: expect.stringContaining(invalidInput),
	})
	expect(mockModule.createStubSavedPackage).not.toHaveBeenCalled()
	expect(mockModule.resolvePackageOwnerContext).not.toHaveBeenCalled()

	resetMocks()
	mockModule.getSavedPackageById.mockResolvedValue(null)
	await expect(getRemote({ package_id: 'missing' })).rejects.toThrow(
		'Saved package "missing" was not found.',
	)

	resetMocks()
	mockPackageSource('other-user')
	await expect(getRemote({ package_id: 'package-1' })).rejects.toThrow(
		'Repo source was not found for this user.',
	)
})

test('get_git_remote returns scoped write and read artifact remotes', async () => {
	resetMocks()
	const { createToken, remote } = mockPackageSource()
	const before = Date.now()
	const writeResult = await getRemote({
		package_id: 'package-1',
		ttl_seconds: 1800,
	})
	const writeExpiresAt = new Date(writeResult.expires_at).getTime()
	expect(createToken.mock.calls).toEqual([['write', 1800]])
	expect(
		mockModule.markEntitySourcePendingExternalReconcile,
	).toHaveBeenCalledWith(expect.anything(), {
		id: 'source-1',
		userId: 'user-1',
		tokenExpiresAt: writeResult.expires_at,
	})
	expect(writeResult).toMatchObject({
		package_id: 'package-1',
		kody_id: 'unleashed-wifi',
		created: false,
		remote,
		scope: 'write',
		git_extra_header: 'Authorization: Bearer art_v1_write_token',
		git_author: { name: 'user-1', email: 'user-1@example.com' },
	})
	expect(writeExpiresAt).toBeGreaterThanOrEqual(before + 1799 * 1000)
	expect(writeExpiresAt).toBeLessThanOrEqual(Date.now() + 1801 * 1000)
	expect(writeResult.authenticated_remote).toContain(
		'https://x:art_v1_write_token@',
	)
	expect(writeResult.setup_commands.length).toBeGreaterThan(0)
	expect(
		writeResult.setup_commands.every((command) => typeof command === 'string'),
	).toBe(true)
	expect(mockModule.listServerRefs).toHaveBeenCalledWith(
		expect.objectContaining({
			protocolVersion: 1,
			prefix: 'refs/heads/main',
		}),
	)

	resetMocks()
	const readSetup = mockPackageSource()
	const readResult = await getRemote({
		kody_id: 'unleashed-wifi',
		scope: 'read',
	})
	expect(readSetup.createToken.mock.calls).toEqual([['read', 14_400]])
	expect(readResult).toMatchObject({
		scope: 'read',
		remote: readSetup.remote,
		git_extra_header: 'Authorization: Bearer art_v1_read_token',
	})
	expect(readResult.authenticated_remote).toContain(
		'https://x:art_v1_read_token@',
	)
	expect(readResult.setup_commands[0]).toMatch(/^git -c http\.extraHeader=/)
	expect(readResult.setup_commands.at(-1)).toContain("HEAD:'main'")
	expect(
		mockModule.markEntitySourcePendingExternalReconcile,
	).not.toHaveBeenCalled()
})

test('get_git_remote retries remote timeouts and write scope blocks without a restorable backup snapshot', async () => {
	resetMocks()
	mockPackageSource()
	const timeout = new Error('Artifacts git request timed out after 8000ms.')
	timeout.name = 'ArtifactsGitTimeoutError'
	mockModule.listServerRefs.mockRejectedValue(timeout)
	await expect(getRemote({ package_id: 'package-1' })).rejects.toThrow(
		/packageGetGitRemote timed out reading the Artifacts git remote[\s\S]*packageSave/,
	)
	expect(mockModule.listServerRefs).toHaveBeenCalledTimes(3)

	resetMocks()
	mockPackageSource()
	await expect(
		getRemote({ package_id: 'package-1', scope: 'write' }, { snapshot: null }),
	).rejects.toThrow('Stop and report this source recovery problem')
})

test('get_git_remote create mode registers stubs for owner and delegated scopes', async () => {
	resetMocks()
	stubCreatedPackage()
	const createdResult = await getRemote({
		kody_id: 'unleashed-wifi',
		create: true,
		description: 'WiFi controls',
	})
	expect(mockModule.createStubSavedPackage).toHaveBeenCalledWith(
		expect.objectContaining({
			kodyId: 'unleashed-wifi',
			description: 'WiFi controls',
			baseUrl: 'https://heykody.dev',
			owner: personalOwner,
		}),
	)
	expect(createdResult).toMatchObject({
		created: true,
		package_id: 'package-1',
		kody_id: 'unleashed-wifi',
	})
	expect(createdResult.setup_commands.length).toBeGreaterThan(0)

	resetMocks()
	mockPackageSource()
	const existingResult = await getRemote({
		kody_id: 'unleashed-wifi',
		create: true,
	})
	expect(mockModule.createStubSavedPackage).not.toHaveBeenCalled()
	expect(existingResult).toMatchObject({
		created: false,
		package_id: 'package-1',
	})

	resetMocks()
	stubCreatedPackage()
	const trimmedResult = await getRemote({
		kody_id: '  unleashed-wifi  ',
		create: true,
	})
	expect(mockModule.resolveSavedPackageRef).toHaveBeenNthCalledWith(
		1,
		expect.anything(),
		expect.objectContaining({ ref: 'unleashed-wifi' }),
	)
	expect(mockModule.createStubSavedPackage).toHaveBeenCalledWith(
		expect.objectContaining({ kodyId: 'unleashed-wifi' }),
	)
	expect(trimmedResult).toMatchObject({
		created: true,
		kody_id: 'unleashed-wifi',
	})

	resetMocks()
	const delegatedOwner = {
		ownerUserId: 'platform-owner',
		ownerScope: 'kody',
		ownerEmail: 'kody@example.com',
		actorUserId: 'user-1',
		delegated: true,
	}
	mockModule.resolvePackageOwnerContext.mockResolvedValue(delegatedOwner)
	stubCreatedPackage('platform-owner', '@kody/unleashed-wifi')
	const delegatedResult = await getRemote({
		kody_id: 'unleashed-wifi',
		create: true,
		package_scope: 'kody',
	})
	expect(mockModule.resolvePackageOwnerContext).toHaveBeenCalledWith(
		expect.anything(),
		expect.objectContaining({ userId: 'user-1' }),
		'kody',
	)
	const ownerLookup = [
		expect.anything(),
		expect.objectContaining({
			userId: 'platform-owner',
			ref: 'unleashed-wifi',
		}),
	]
	expect(mockModule.resolveSavedPackageRef.mock.calls).toEqual([
		ownerLookup,
		ownerLookup,
	])
	expect(mockModule.createStubSavedPackage).toHaveBeenCalledWith(
		expect.objectContaining({
			owner: delegatedOwner,
			kodyId: 'unleashed-wifi',
		}),
	)
	expect(delegatedResult).toMatchObject({
		created: true,
		package_id: 'package-1',
	})
})
