import { expect, test } from 'vitest'
import {
	attributeGeneratedBytes,
	diffAttributedSources,
	formatAttributedSources,
	formatSourceByteDeltas,
	parseStartupBundleCheckArgs,
} from './startup-bundle-attribution.ts'

const vlqAlphabet =
	'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/'

function encodeVlq(value: number) {
	let vlq = value < 0 ? (-value << 1) | 1 : value << 1
	let encoded = ''
	do {
		let digit = vlq & 31
		vlq >>= 5
		if (vlq > 0) digit |= 32
		encoded += vlqAlphabet[digit]
	} while (vlq > 0)
	return encoded
}

function mappingSegment(
	generatedColumn: number,
	sourceIndex = 0,
	sourceLine = 0,
	sourceColumn = 0,
) {
	return [
		encodeVlq(generatedColumn),
		encodeVlq(sourceIndex),
		encodeVlq(sourceLine),
		encodeVlq(sourceColumn),
	].join('')
}

test('startup bundle check args enable attribution and outdir compare', () => {
	expect(parseStartupBundleCheckArgs([])).toEqual({
		attribute: false,
		base: null,
		keepOutdir: null,
		compareOutdir: null,
	})
	expect(
		parseStartupBundleCheckArgs([
			'--attribute',
			'--base',
			'.tmp/startup-main',
			'--keep-outdir',
			'.tmp/startup-head',
		]),
	).toEqual({
		attribute: true,
		base: '.tmp/startup-main',
		keepOutdir: '.tmp/startup-head',
		compareOutdir: null,
	})
	expect(
		parseStartupBundleCheckArgs(['--compare-outdir', '.tmp/startup-main']),
	).toEqual({
		attribute: true,
		base: null,
		keepOutdir: null,
		compareOutdir: '.tmp/startup-main',
	})
	expect(() => parseStartupBundleCheckArgs(['--unknown'])).toThrow(
		/Unknown argument/,
	)
})

test('source-map attribution sums generated bytes per original source', () => {
	const generated = 'aaaabbbb'
	const sourceMap = JSON.stringify({
		version: 3,
		sources: ['packages/worker/src/a.ts', 'packages/worker/src/b.ts'],
		mappings: `${mappingSegment(0, 0)},${mappingSegment(4, 1)}`,
	})
	expect(attributeGeneratedBytes(generated, sourceMap)).toEqual([
		{ source: 'packages/worker/src/a.ts', bytes: 4 },
		{ source: 'packages/worker/src/b.ts', bytes: 4 },
	])

	const grown = attributeGeneratedBytes(`${generated}cccc`, sourceMap)
	const deltas = diffAttributedSources(grown, [
		{ source: 'packages/worker/src/a.ts', bytes: 4 },
		{ source: 'packages/worker/src/b.ts', bytes: 4 },
	])
	expect(deltas[0]).toMatchObject({
		source: 'packages/worker/src/b.ts',
		delta: 4,
	})
	expect(formatAttributedSources(grown)).toContain('packages/worker/src/a.ts')
	expect(formatSourceByteDeltas(deltas)).toMatch(/\+4/)

	const withNewline = attributeGeneratedBytes(`${generated}\n`, sourceMap)
	expect(withNewline.reduce((sum, entry) => sum + entry.bytes, 0)).toBe(
		generated.length + 1,
	)

	const unmappedMap = JSON.stringify({
		version: 3,
		sources: ['packages/worker/src/a.ts'],
		mappings: `${mappingSegment(0, 0)},${encodeVlq(4)}`,
	})
	expect(attributeGeneratedBytes('aaaabbbb', unmappedMap)).toEqual([
		{ source: 'packages/worker/src/a.ts', bytes: 4 },
	])
})
